### ISSUE TITLE
IndexError: list index out of range in /tools/parse.py line 59

### ISSUE THREAD

**Issue by antonakv** [conor-or/fb-analysis#2]
Hi,
there is some problem:

$ python main.py /Users/a/index.htm 

    Facebook Group Chat Analysis
    Conor O'Riordan
    Apr 2017
    
    Check the README at github.com/conor-or/fb-analysis or
    type groupchat.help() to see what you can do.
    
No pkl file found, parsing HTML...
Found file index.htm
Parsing HTML (may take a while)...
Traceback (most recent call last):
  File "main.py", line 557, in <module>
    groupchat = messages_load()
  File "main.py", line 527, in messages_load
    thread_parse(sys.argv[1])
  File "/Users/a/fb-analysis/tools/parse.py", line 59, in thread_parse
    thread = soup.findAll('div', {'class': 'thread'})[0]
IndexError: list index out of range

---

Captured file reads before crash
```Shell
23:29:32  lstat64           /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_size.py      0.000008   com.avast.da
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_size.py      0.000009   com.avast.da
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_size.py      0.007392   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1                   0.000021   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_size.pyc     0.000011   Python      
23:29:32  stat64            /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_divider      0.000022   Python      
23:29:32  open              usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_divider.so    0.000011   Python      
23:29:32  open              cal/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_dividermodule.so    0.000009   Python      
23:29:32  open              usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_divider.py    0.000012   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1                   0.000006   Python      
23:29:32  open              sr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_divider.pyc    0.000009   Python      
23:29:32  stat64            /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/mpl_axes          0.000013   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/mpl_axes.so       0.000010   Python      
23:29:32  open              r/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/mpl_axesmodule.so    0.000008   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/mpl_axes.py       0.000011   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1                   0.000006   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/mpl_axes.pyc      0.000009   Python      
23:29:32  stat64            /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_grid         0.000013   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_grid.so      0.000009   Python      
23:29:32  open              /local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_gridmodule.so    0.000008   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_grid.py      0.000010   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1                   0.000006   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/axes_grid.pyc     0.000010   Python      
23:29:32  stat64            /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/colorbar          0.000012   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/colorbar.so       0.000009   Python      
23:29:32  open              r/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/colorbarmodule.so    0.000008   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/colorbar.py       0.000010   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1                   0.000005   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/colorbar.pyc      0.000008   Python      
23:29:32  stat64            /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/parasite_axes     0.000012   Python      
23:29:32  open              sr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/parasite_axes.so    0.000009   Python      
23:29:32  open              al/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/parasite_axesmodule.so    0.000008   Python      
23:29:32  open              sr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py    0.000010   Python      
23:29:32  open              /usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1                   0.000005   Python      
23:29:32  open              r/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/parasite_axes.pyc    0.000009   Python
```

**Comment by antonakv** [comment]
https://stackoverflow.com/questions/42532605/beautiful-soup-crashes-python-process

**Comment by greenbagels** [comment]
I don't think you're supposed to be running it on the `index.htm` file from the zip. Have you tried running it on any of the html files from the `messages` folder?

**Comment by antonakv** [comment]
Yes, you're right. I expected script can do reports for Facebook groups, not chats.
